name: AEMaaCS

on: [ push, pull_request ]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-cloud
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build for AEM Cloud SDK
        run: mvn --batch-mode --update-snapshots --activate-profiles cloud install
