name: Publish package to the GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish package
        run: mvn --batch-mode deploy --activate-profiles github-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
