name: Release to Maven Central

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Remove SNAPSHOT from version
        run: mvn versions:set -DremoveSnapshot versions:commit

      - name: Deploy package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Next SNAPSHOT version
        run: mvn versions:set -DnextSnapshot versions:commit

      - name: Update changelog
        id: update-changelog
        uses: release-flow/keep-a-changelog-action/prepare-release@v1
        with:
          release-type: patch

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: all/target/aem-groovy-console-all-*.zip
          body: ${{ steps.update-changelog.outputs.release-notes }}

      - uses: stefanzweifel/git-auto-commit-action@v4
